// ============================================
// MATTRESS DATABASE with Logo Paths
// Shared between main.js and detailed-comparison.js
// ============================================

const mattressData = {
    "Casper": {
        logo: "assets/images/brands/casper-logo.png",
        type: "Memory Foam / Hybrid",
        comfort: "Medium-firm, zoned support",
        value: "Great value — top rated",
        price: "$1,095 – $2,295",
        priceValue: 1200,
        materials: "AirScape foam, zoned support",
        firmness: 6.5,
        firmnessText: "Medium-firm",
        rating: 4.8,
        bestFor: "Back sleepers, couples",
        sleepPosition: ["back", "combination"],
        tagline: "Engineered for the way you sleep",
        warranty: "10 years limited",
        trial: "100 nights",
        cooling: "AirScape breathable foam",
        motionIsolation: "Excellent",
        edgeSupport: "Good",
        sizes: ["Twin", "Twin XL", "Full", "Queen", "King", "Cal King"],
        shipping: "Free shipping, compressed in a box",
        scores: { type: 8, support: 9, value: 9, price: 7, materials: 8 },
        accentColor: "#2C5F8A",
        expertSummary: "The Casper Original features Zoned Support that provides targeted pressure relief. Its AirScape foam keeps sleepers cool while delivering balanced comfort.",
        customerRatingCount: 429,
        customerComfort: 4.7,
        customerSupport: 4.6,
        customerCooling: 4.4,
        keyFeatures: ["Cooling", "Zoned Support", "Medium-firm", "Motion Isolation"]
    },
    "Leesa": {
        logo: "assets/images/brands/leesa-logo.png",
        type: "Foam / Hybrid",
        comfort: "Medium-firm, pressure relief",
        value: "High value, social impact",
        price: "$999 – $2,099",
        priceValue: 1000,
        materials: "3-layer foam, cooling top",
        firmness: 6,
        firmnessText: "Medium",
        rating: 4.7,
        bestFor: "All sleep positions",
        sleepPosition: ["back", "side", "stomach", "combination"],
        tagline: "Sleep better, do good",
        warranty: "10 years",
        trial: "100 nights",
        cooling: "Cooling top layer, breathable foam",
        motionIsolation: "Excellent",
        edgeSupport: "Very Good",
        sizes: ["Twin", "Twin XL", "Full", "Queen", "King", "Cal King"],
        shipping: "Free shipping & returns",
        scores: { type: 8, support: 9, value: 9, price: 8, materials: 8 },
        accentColor: "#4A6A5E",
        expertSummary: "Leesa combines three premium foam layers for universal comfort. Known for pressure relief and excellent motion isolation, it's ideal for all sleep positions.",
        customerRatingCount: 272,
        customerComfort: 4.8,
        customerSupport: 4.7,
        customerCooling: 4.5,
        keyFeatures: ["Pressure Relief", "Universal Comfort", "Cooling Top", "Eco-friendly"]
    },
    "Purple": {
        logo: "assets/images/brands/purple-logo.png",
        type: "Hyper-Elastic Polymer",
        comfort: "Soft yet supportive, cooling grid",
        value: "Premium cooling technology",
        price: "$1,399 – $3,498",
        priceValue: 1800,
        materials: "Purple Grid, breathable cover",
        firmness: 5,
        firmnessText: "Medium-soft",
        rating: 4.6,
        bestFor: "Hot sleepers, combo sleepers",
        sleepPosition: ["side", "combination"],
        tagline: "No pressure, all comfort",
        warranty: "10 years",
        trial: "100 nights",
        cooling: "Purple Grid hyper-elastic polymer",
        motionIsolation: "Very Good",
        edgeSupport: "Good",
        sizes: ["Twin", "Twin XL", "Full", "Queen", "King", "Cal King", "Split King"],
        shipping: "Free shipping",
        scores: { type: 9, support: 8, value: 8, price: 6, materials: 9 },
        accentColor: "#6A1B9A",
        expertSummary: "The Purple Grid flexes under pressure points while supporting the rest of the body. It's uniquely cooling and ideal for hot sleepers.",
        customerRatingCount: 512,
        customerComfort: 4.6,
        customerSupport: 4.5,
        customerCooling: 4.9,
        keyFeatures: ["Hyper-Elastic Grid", "Cooling", "Pressure Relief", "Durable"]
    },
    "Nest Bedding": {
        logo: "assets/images/brands/nest-bedding-logo.png",
        type: "Hybrid / Latex",
        comfort: "Customizable firmness",
        value: "Organic, eco-friendly",
        price: "$1,099 – $2,399",
        priceValue: 1500,
        materials: "Organic cotton, natural latex",
        firmness: 6,
        firmnessText: "Selectable",
        rating: 4.9,
        bestFor: "Eco-conscious shoppers",
        sleepPosition: ["back", "side", "stomach", "combination"],
        tagline: "Handcrafted in the USA",
        warranty: "Lifetime",
        trial: "365 nights",
        cooling: "Natural latex, breathable cover",
        motionIsolation: "Good",
        edgeSupport: "Excellent",
        sizes: ["Twin", "Twin XL", "Full", "Queen", "King", "Cal King"],
        shipping: "Free white glove delivery",
        scores: { type: 9, support: 9, value: 9, price: 7, materials: 10 },
        accentColor: "#2E7D64",
        expertSummary: "Nest Bedding offers customizable firmness and organic materials. It's one of the most eco-friendly luxury mattresses on the market.",
        customerRatingCount: 348,
        customerComfort: 4.9,
        customerSupport: 4.8,
        customerCooling: 4.6,
        keyFeatures: ["Organic", "Customizable", "Eco-friendly", "Handcrafted"]
    },
    "Saatva": {
        logo: "assets/images/brands/saatva-logo.png",
        type: "Innerspring Hybrid",
        comfort: "Lumbar support, luxury feel",
        value: "Premium, eco-friendly",
        price: "$1,295 – $2,590",
        priceValue: 1600,
        materials: "Organic cotton, coil-on-coil",
        firmness: 7,
        firmnessText: "Medium-firm to firm",
        rating: 4.9,
        bestFor: "Back pain sufferers",
        sleepPosition: ["back", "stomach"],
        tagline: "Luxury without the markup",
        warranty: "Lifetime",
        trial: "365 nights",
        cooling: "Organic cotton cover, breathable coils",
        motionIsolation: "Fair",
        edgeSupport: "Excellent",
        sizes: ["Twin", "Twin XL", "Full", "Queen", "King", "Cal King", "Split King"],
        shipping: "Free white glove delivery",
        scores: { type: 8, support: 10, value: 9, price: 7, materials: 9 },
        accentColor: "#B76E2E",
        expertSummary: "Saatva's coil-on-coil construction provides exceptional lumbar support. It's a favorite among those with back pain.",
        customerRatingCount: 892,
        customerComfort: 4.8,
        customerSupport: 4.9,
        customerCooling: 4.7,
        keyFeatures: ["Lumbar Support", "Luxury", "Organic", "Spinal Alignment"]
    },
    "Helix": {
        logo: "assets/images/brands/helix-logo.png",
        type: "Hybrid (Personalized)",
        comfort: "Tailored to your body",
        value: "High customization",
        price: "$936 – $2,349",
        priceValue: 1100,
        materials: "DuraDense foam, wrapped coils",
        firmness: 5.5,
        firmnessText: "Customizable",
        rating: 4.7,
        bestFor: "Personalized comfort",
        sleepPosition: ["back", "side", "stomach", "combination"],
        tagline: "Made for you",
        warranty: "10 years",
        trial: "100 nights",
        cooling: "Gel-infused foam, breathable cover",
        motionIsolation: "Good",
        edgeSupport: "Very Good",
        sizes: ["Twin", "Twin XL", "Full", "Queen", "King", "Cal King"],
        shipping: "Free shipping",
        scores: { type: 9, support: 9, value: 8, price: 8, materials: 8 },
        accentColor: "#00A86B",
        expertSummary: "Helix offers a personalized sleep experience with a quiz that matches you to the perfect firmness and support level.",
        customerRatingCount: 567,
        customerComfort: 4.7,
        customerSupport: 4.7,
        customerCooling: 4.5,
        keyFeatures: ["Personalized", "Hybrid", "Cooling", "Custom Firmness"]
    },
    "Tempur-Pedic": {
        logo: "assets/images/brands/tempur-pedic-logo.png",
        type: "Memory Foam",
        comfort: "Deep contouring, pressure relief",
        value: "Luxury, long-lasting",
        price: "$1,899 – $5,000+",
        priceValue: 3000,
        materials: "Tempur material, cooling tech",
        firmness: 6,
        firmnessText: "Soft to firm options",
        rating: 4.8,
        bestFor: "Pressure point relief",
        sleepPosition: ["back", "side"],
        tagline: "The original memory foam",
        warranty: "10 years",
        trial: "90 nights",
        cooling: "Tempur-APR+ cooling",
        motionIsolation: "Superior",
        edgeSupport: "Excellent",
        sizes: ["Twin", "Twin XL", "Full", "Queen", "King", "Cal King", "Split King"],
        shipping: "White glove delivery",
        scores: { type: 9, support: 10, value: 7, price: 4, materials: 10 },
        accentColor: "#8B4513",
        expertSummary: "Tempur-Pedic's proprietary memory foam conforms to your body for unparalleled pressure relief and motion isolation.",
        customerRatingCount: 1245,
        customerComfort: 4.8,
        customerSupport: 4.9,
        customerCooling: 4.3,
        keyFeatures: ["Memory Foam", "Pressure Relief", "Motion Isolation", "Premium"]
    },
    "DreamCloud": {
        logo: "assets/images/brands/dreamcloud-logo.png",
        type: "Hybrid Luxury",
        comfort: "Medium-firm, cashmere cover",
        value: "Luxury at accessible price",
        price: "$899 – $1,399",
        priceValue: 1000,
        materials: "Gel foam, innerspring coils",
        firmness: 6.5,
        firmnessText: "Medium-firm",
        rating: 4.7,
        bestFor: "Luxury on a budget",
        sleepPosition: ["back", "stomach"],
        tagline: "Luxury you can afford",
        warranty: "Lifetime",
        trial: "365 nights",
        cooling: "Gel memory foam, cashmere cover",
        motionIsolation: "Good",
        edgeSupport: "Excellent",
        sizes: ["Twin", "Twin XL", "Full", "Queen", "King", "Cal King"],
        shipping: "Free white glove delivery",
        scores: { type: 8, support: 8, value: 9, price: 9, materials: 8 },
        accentColor: "#4B6A9B",
        expertSummary: "DreamCloud brings luxury hybrid construction at an accessible price point with a lifetime warranty and 365-night trial.",
        customerRatingCount: 734,
        customerComfort: 4.7,
        customerSupport: 4.6,
        customerCooling: 4.5,
        keyFeatures: ["Luxury Hybrid", "Cashmere Cover", "Lifetime Warranty", "Value"]
    }
};